name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ubuntu@YOUR_EC2_IP 'bash -s' <<'EOF'
        cd /path/to/your/project
        git pull origin main
        sudo systemctl restart nginx
        sudo systemctl restart gunicorn
        EOF
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - name: Create SSH key file
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
