# Generated by Django 4.2 on 2024-04-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_comment_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
